/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registro;

import java.awt.BorderLayout;

/**
 *
 * @author josep
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Registros
     */
    public Principal() {
        initComponents();
        
        RegistroVenta p1 = new RegistroVenta();
        p1.setSize(630, 440);
        p1.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        navegador = new javax.swing.JPanel();
        btnRegistroVenta = new javax.swing.JLabel();
        btnRegistroProducto = new javax.swing.JLabel();
        Reporte = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        datos_usuario = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navegador.setBackground(new java.awt.Color(244, 133, 3));

        btnRegistroVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroVenta.setText("Registro de Venta");
        btnRegistroVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistroVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroVentaMouseClicked(evt);
            }
        });

        btnRegistroProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroProducto.setText("Registro de Producto");
        btnRegistroProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistroProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroProductoMouseClicked(evt);
            }
        });

        Reporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reporte.setText("Reporte");
        Reporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReporteMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Santa Rosa.png"))); // NOI18N

        javax.swing.GroupLayout navegadorLayout = new javax.swing.GroupLayout(navegador);
        navegador.setLayout(navegadorLayout);
        navegadorLayout.setHorizontalGroup(
            navegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegadorLayout.createSequentialGroup()
                .addGroup(navegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navegadorLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(49, 49, 49))
        );
        navegadorLayout.setVerticalGroup(
            navegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegadorLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addComponent(btnRegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistroProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        body.add(navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        datos_usuario.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout datos_usuarioLayout = new javax.swing.GroupLayout(datos_usuario);
        datos_usuario.setLayout(datos_usuarioLayout);
        datos_usuarioLayout.setHorizontalGroup(
            datos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        datos_usuarioLayout.setVerticalGroup(
            datos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        body.add(datos_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 630, -1));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        body.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 630, 440));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVentaMouseClicked
       RegistroVenta p1 = new RegistroVenta();
        p1.setSize(630, 440);
        p1.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnRegistroVentaMouseClicked

    private void btnRegistroProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroProductoMouseClicked
        RegistroProducto p2 = new RegistroProducto();
        p2.setSize(630, 440);
        p2.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p2,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnRegistroProductoMouseClicked

    private void ReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteMouseClicked
       Reporte p3 = new Reporte();
        p3.setSize(630, 440);
        p3.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p3,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_ReporteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Reporte;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnRegistroProducto;
    private javax.swing.JLabel btnRegistroVenta;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel datos_usuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel navegador;
    // End of variables declaration//GEN-END:variables
}
