/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registro;

import java.awt.BorderLayout;
import java.awt.Color;
import Registro.Login;
import javax.print.attribute.standard.DateTimeAtCompleted;

/**
 *
 * @author josep
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Registros
     */
    int xMouse, yMouse;
    public Principal() {
        initComponents();
        
        Login lo = new Login();
        String ape = new Controller.PrincipalController().Apellido(lo.usuario);
        jLabelNombreUsuario.setText(lo.usuario + " "+ape);
        
        
        RegistroVenta p1 = new RegistroVenta();
        p1.setSize(630, 440);
        p1.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        navegador = new javax.swing.JPanel();
        btnRegistroProducto = new javax.swing.JLabel();
        btnReporte = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JLabel();
        btnRegistroVenta = new javax.swing.JLabel();
        datos_usuario = new javax.swing.JPanel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        LabelExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navegador.setBackground(new java.awt.Color(244, 133, 3));
        navegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistroProducto.setBackground(new java.awt.Color(255, 153, 51));
        btnRegistroProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistroProducto.setText("Registro de Producto");
        btnRegistroProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroProducto.setOpaque(true);
        btnRegistroProducto.setPreferredSize(new java.awt.Dimension(142, 24));
        btnRegistroProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroProductoMouseExited(evt);
            }
        });
        navegador.add(btnRegistroProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 60));

        btnReporte.setBackground(new java.awt.Color(255, 153, 51));
        btnReporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReporte.setText("Reporte");
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.setOpaque(true);
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
        });
        navegador.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 54));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Santa Rosa.png"))); // NOI18N
        navegador.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 53, -1, -1));

        btnConsulta.setBackground(new java.awt.Color(255, 153, 51));
        btnConsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsulta.setText("Consulta");
        btnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta.setOpaque(true);
        btnConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultaMouseExited(evt);
            }
        });
        navegador.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 60));

        btnRegistroVenta.setBackground(new java.awt.Color(255, 153, 51));
        btnRegistroVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistroVenta.setText("Registro de Venta");
        btnRegistroVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroVenta.setOpaque(true);
        btnRegistroVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroVentaMouseExited(evt);
            }
        });
        navegador.add(btnRegistroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 270, 58));

        body.add(navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 540));

        datos_usuario.setBackground(new java.awt.Color(255, 204, 102));

        jLabelNombreUsuario.setBackground(new java.awt.Color(255, 204, 102));
        jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreUsuario.setOpaque(true);
        jLabelNombreUsuario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelNombreUsuarioComponentAdded(evt);
            }
        });
        jLabelNombreUsuario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabelNombreUsuarioInputMethodTextChanged(evt);
            }
        });

        jLabelFecha.setBackground(new java.awt.Color(255, 204, 102));
        jLabelFecha.setOpaque(true);

        javax.swing.GroupLayout datos_usuarioLayout = new javax.swing.GroupLayout(datos_usuario);
        datos_usuario.setLayout(datos_usuarioLayout);
        datos_usuarioLayout.setHorizontalGroup(
            datos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datos_usuarioLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        datos_usuarioLayout.setVerticalGroup(
            datos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datos_usuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(datos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        body.add(datos_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 630, 70));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        body.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 630, 440));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelExit.setBackground(new java.awt.Color(255, 255, 255));
        LabelExit.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelExit.setText("X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelExit.setOpaque(true);
        LabelExit.setPreferredSize(new java.awt.Dimension(30, 30));
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        header.add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 100));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVentaMouseClicked
       RegistroVenta p1 = new RegistroVenta();
        p1.setSize(630, 440);
        p1.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnRegistroVentaMouseClicked

    private void btnRegistroProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroProductoMouseClicked
        RegistroProducto p2 = new RegistroProducto();
        p2.setSize(630, 440);
        p2.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p2,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnRegistroProductoMouseClicked

    private void btnReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseClicked
       Reporte p3 = new Reporte();
        p3.setSize(630, 440);
        p3.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p3,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnReporteMouseClicked

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LabelExitMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseClicked
        // TODO add your handling code here:
        Consultas p4 = new Consultas();
        p4.setSize(630, 440);
        p4.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p4,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnConsultaMouseClicked

    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        // TODO add your handling code here:
        LabelExit.setBackground(Color.red);
        LabelExit.setForeground(Color.white);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        // TODO add your handling code here:
        LabelExit.setBackground(Color.white);
        LabelExit.setForeground(Color.black);
    }//GEN-LAST:event_LabelExitMouseExited

    private void btnRegistroVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVentaMouseEntered
        // TODO add your handling code here:
        btnRegistroVenta.setBackground(new  Color(255, 204, 102));
        btnRegistroVenta.setForeground(Color.white);
    }//GEN-LAST:event_btnRegistroVentaMouseEntered

    private void btnRegistroVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVentaMouseExited
        // TODO add your handling code here:
        btnRegistroVenta.setBackground(new  Color(255, 153, 51));
        btnRegistroVenta.setForeground(Color.black);
    }//GEN-LAST:event_btnRegistroVentaMouseExited

    private void btnRegistroProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroProductoMouseEntered
        // TODO add your handling code here:
        btnRegistroProducto.setBackground(new  Color(255, 204, 102));
        btnRegistroProducto.setForeground(Color.white);
    }//GEN-LAST:event_btnRegistroProductoMouseEntered

    private void btnRegistroProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroProductoMouseExited
        // TODO add your handling code here:
        btnRegistroProducto.setBackground(new  Color(255, 153, 51));
        btnRegistroProducto.setForeground(Color.black);
    }//GEN-LAST:event_btnRegistroProductoMouseExited

    private void btnConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseEntered
        // TODO add your handling code here:
        btnConsulta.setBackground(new  Color(255, 204, 102));
        btnConsulta.setForeground(Color.white);
    }//GEN-LAST:event_btnConsultaMouseEntered

    private void btnConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseExited
        // TODO add your handling code here:
        btnConsulta.setBackground(new  Color(255, 153, 51));
        btnConsulta.setForeground(Color.black);
    }//GEN-LAST:event_btnConsultaMouseExited

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered
        // TODO add your handling code here:
        btnReporte.setBackground(new  Color(255, 204, 102));
        btnReporte.setForeground(Color.white);
    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        // TODO add your handling code here:
        btnReporte.setBackground(new  Color(255, 153, 51));
        btnReporte.setForeground(Color.black);
    }//GEN-LAST:event_btnReporteMouseExited

    private void jLabelNombreUsuarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelNombreUsuarioComponentAdded

    }//GEN-LAST:event_jLabelNombreUsuarioComponentAdded

    private void jLabelNombreUsuarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabelNombreUsuarioInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNombreUsuarioInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelExit;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnConsulta;
    private javax.swing.JLabel btnRegistroProducto;
    private javax.swing.JLabel btnRegistroVenta;
    private javax.swing.JLabel btnReporte;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel datos_usuario;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JPanel navegador;
    // End of variables declaration//GEN-END:variables
}
